import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import StyledComponentsRegistry from '@/lib/AntdRegistry';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="p-2 pl-4 flex ">
                    <Link href="/">
                        <h1 className="font-bold text-[32px] cursor-pointer">
                            MyTube
                        </h1>
                    </Link>
                </div>
                <StyledComponentsRegistry>
                    <div className="py-12 px-24">{children}</div>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
